import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../utils/theme.dart';
import '../../widgets/apple_widgets.dart';
import '../../services/supabase_service.dart';
import '../../models/ad_model.dart';
import '../../providers/auth_provider.dart';

class AdPromotionScreen extends StatefulWidget {
  const AdPromotionScreen({super.key});

  @override
  State<AdPromotionScreen> createState() => _AdPromotionScreenState();
}

class _AdPromotionScreenState extends State<AdPromotionScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  int _selectedTier = 1; // 1: Standard, 2: Gold, 3: Platinum
  bool _isLoading = false;

  final List<Map<String, dynamic>> _tiers = [
    {
      'level': 1,
      'name': 'Standard Boost',
      'price': '50 MAD',
      'duration': '3 Days',
      'color': Colors.blue,
      'icon': Icons.flash_on_rounded,
    },
    {
      'level': 2,
      'name': 'Gold Spotlight',
      'price': '120 MAD',
      'duration': '7 Days',
      'color': Colors.orange,
      'icon': Icons.star_rounded,
    },
    {
      'level': 3,
      'name': 'Platinum Premium',
      'price': '300 MAD',
      'duration': '30 Days',
      'color': Colors.deepPurple,
      'icon': Icons.diamond_rounded,
    },
  ];

  Future<void> _createPromotion() async {
    if (!_formKey.currentState!.validate()) return;
    
    // Simulate payment
    setState(() => _isLoading = true);
    await Future.delayed(const Duration(seconds: 2));

    final user = context.read<AuthProvider>().user;
    if (user == null) return;

    final expiryDays = _selectedTier == 1 ? 3 : (_selectedTier == 2 ? 7 : 30);
    
    final ad = AdModel(
      id: '', // Generated by DB
      providerId: user.id,
      title: _titleController.text,
      description: _descController.text,
      expiresAt: DateTime.now().add(Duration(days: expiryDays)),
      priorityLevel: _selectedTier,
    );

    try {
      await SupabaseService().createAd(ad);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Promotion created successfully! 🚀')),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundWhite,
      appBar: AppBar(
        title: Text("Promote Your Service", style: AppTheme.textTheme.headlineMedium),
        centerTitle: true,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
               Text(
                "Reach more customers by boosting your profile to the top of search results.",
                style: AppTheme.textTheme.bodyMedium,
              ),
              const SizedBox(height: 32),

              Text("Select Plan", style: AppTheme.textTheme.titleLarge),
              const SizedBox(height: 16),
              
              ..._tiers.map((tier) {
                final isSelected = _selectedTier == tier['level'];
                return Padding(
                  padding: const EdgeInsets.only(bottom: 16),
                  child: GestureDetector(
                    onTap: () => setState(() => _selectedTier = tier['level']),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: isSelected ? Colors.white : Colors.white.withOpacity(0.5),
                        borderRadius: BorderRadius.circular(24),
                        border: Border.all(
                          color: isSelected ? tier['color'] : Colors.transparent,
                          width: 2,
                        ),
                        boxShadow: isSelected ? [
                          BoxShadow(color: (tier['color'] as Color).withOpacity(0.3), blurRadius: 20, offset: const Offset(0, 8))
                        ] : [],
                      ),
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: (tier['color'] as Color).withOpacity(0.1),
                              shape: BoxShape.circle,
                            ),
                            child: Icon(tier['icon'], color: tier['color'], size: 28),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(tier['name'], style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                Text(tier['duration'], style: TextStyle(color: Colors.grey[600], fontSize: 13)),
                              ],
                            ),
                          ),
                          Text(tier['price'], style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 18)),
                        ],
                      ),
                    ),
                  ),
                );
              }),

              const SizedBox(height: 32),
              Text("Ad Details", style: AppTheme.textTheme.titleLarge),
              const SizedBox(height: 16),

              AppleGlassContainer(
                child: Column(
                  children: [
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'Headline',
                        hintText: 'e.g., Expert Plumbing 24/7',
                        border: InputBorder.none,
                      ),
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                    const Divider(),
                    TextFormField(
                      controller: _descController,
                      decoration: const InputDecoration(
                        labelText: 'Description',
                        hintText: 'Tell customers why they should choose you...',
                        border: InputBorder.none,
                      ),
                      maxLines: 3,
                       validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 48),

              SizedBox(
                width: double.infinity,
                child: AppleButton(
                  onPressed: _isLoading ? null : _createPromotion,
                  child: _isLoading 
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text("Pay & Promote", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }
}
