// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRWwfL9pVT1-DGZVPKshcbBTwldZmVOac',
    appId: '1:137053449392:web:7502b4e79c308afe235f75',
    messagingSenderId: '137053449392',
    projectId: 'khdemti-ma',
    authDomain: 'khdemti-ma.firebaseapp.com',
    storageBucket: 'khdemti-ma.firebasestorage.app',
    measurementId: 'G-1L9WTDC4WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1OLtlPJyekJNMKi8k81AUaEP4jw-LWc',
    appId: '1:137053449392:android:8805d7f7c7b9cc3c235f75',
    messagingSenderId: '137053449392',
    projectId: 'khdemti-ma',
    storageBucket: 'khdemti-ma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZsDQPQRluQLZPsG6PSZEcYY5U1rFobA',
    appId: '1:137053449392:ios:b7f9651fb4ff84b0235f75',
    messagingSenderId: '137053449392',
    projectId: 'khdemti-ma',
    storageBucket: 'khdemti-ma.firebasestorage.app',
    iosBundleId: 'com.zekri.khdemti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZsDQPQRluQLZPsG6PSZEcYY5U1rFobA',
    appId: '1:137053449392:ios:b7f9651fb4ff84b0235f75',
    messagingSenderId: '137053449392',
    projectId: 'khdemti-ma',
    storageBucket: 'khdemti-ma.firebasestorage.app',
    iosBundleId: 'com.zekri.khdemti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRWwfL9pVT1-DGZVPKshcbBTwldZmVOac',
    appId: '1:137053449392:web:3400e040d89e90fa235f75',
    messagingSenderId: '137053449392',
    projectId: 'khdemti-ma',
    authDomain: 'khdemti-ma.firebaseapp.com',
    storageBucket: 'khdemti-ma.firebasestorage.app',
    measurementId: 'G-4FTQ3H77L8',
  );

}